# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      echo Building on Linux
      cd src
      mkdir build
      cd build
      cmake ../
      cmake --build .
      ./hello
    displayName: 'Build on Linux'

- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      echo Building on macOS
      cd src
      mkdir build
      cd build
      cmake ../
      cmake --build .
      hello.exe
    displayName: 'Build on Windows'

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - script: |
      echo Building on macOS
      cd src
      mkdir build
      cd build
      cmake ../
      cmake --build .
      ./hello
    displayName: 'Build on macOS'


