# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      echo Build on Linux
      mkdir build
      cd build
      cmake ..
      cmake --build .
    displayName: 'Build on Linux'
  - script: |
      echo Test on Linux
      echo $BUILD_SOURCESDIRECTORY
      ctest .
    env:
      BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory) 
    workingDirectory: build
    displayName: 'Test on Linux'

- job: Windows
  pool:
    vmImage: 'windows-latest'

  steps:
  - script: |
      echo Build on Windows
      mkdir build
      cd build
      cmake ..
      cmake --build .
    displayName: 'Build on Windows'
  - script: |
      echo Test on Windows
      echo $BUILD_SOURCESDIRECTORY
      ctest .
    env:
      BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory) 
    workingDirectory: build
    displayName: 'Test on Windows'

- job: macOS
  pool:
    vmImage: 'macOS-latest'

  steps:
  - script: |
      echo Build on macOS
      mkdir build
      cd build
      cmake ..
      cmake --build .
    displayName: 'Build on macOS'
  - script: |
      echo Test on macOS
      echo $BUILD_SOURCESDIRECTORY
      ctest .
    env:
      BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory) 
    workingDirectory: build
    displayName: 'Test on macOS'

