# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macOS-latest'
    windows:
      imageName: 'windows-latest'

trigger:
- master

pool:
  vmImage: $(imageName)

steps:
- script: |
    echo Build on $(Agent.OS)
    mkdir build
    cd build
    cmake ..
    cmake --build .
  displayName: 'Build on $(Agent.OS)'
- script: |
    echo Test on $(Agent.OS)
    echo $(CTEST_SOURCE_DIRECTORY)
    echo $(CTEST_BUILD_NAME)
    echo $(CTEST_SITE)
    ctest --verbose -S ../CTestScript.cmake
  env:
    CTEST_SOURCE_DIRECTORY: $(Build.SourcesDirectory)
    CTEST_BUILD_NAME: $(Build.BuildNumber)
    CTEST_SITE: $(Agent.MachineName)
  workingDirectory: build
  displayName: 'Test on $(Agent.OS)'
