name: Publish Release Notice to ASWF Slack

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    Steps:
    - name: Notify Slack
      id: slack
      with:
        project_name: "ASWF Sample Project"
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        project_logo: "https://artwork.aswf.io/other/aswf/text/aqua/aswf-text-aqua.png"
        release_version: ${{ github.event.release.name }}
        release_url: ${{ github.event.release.html_url }}
        release_notes: ${{ github.event.release.body }}
      uses: jmertic/slack-release-notifier@latest
