name: Publish Release Notice to ASWF Slack

on:
  release:
    types:
      - released

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Notify Slack
      id: slack
      with:
        project_name: "ASWF Sample Project"
        slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack_channel: "#test-release-announcements"
        project_logo: "https://artwork.aswf.io/other/aswf/text/aqua/aswf-text-aqua.png"
      uses: jmertic/slack-release-notifier@main
