name: Lint repository
on: [push]

jobs:
  repo-lint:
    name: "repolint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g git+https://github.com/todogroup/repolinter.git
      - run: repolinter lint -g $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
