name: Weekly Lint repository
on: 
  schedule:
    - cron: "0 0 * * 0"

jobs:
  repo-lint:
    name: "repolint"
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install -g github:todogroup/repolinter.git#ae6688cddeed312d45a50d7439ae71383eb660e2
      - run: repolinter lint -g $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
